package main

import (
	"fmt"
	_ "log"
	"os"
	"talui/pkg/app"
	"talui/pkg/database"
	"talui/pkg/route"

	"github.com/gofiber/fiber/v2/middleware/cors"

	_ "github.com/go-sql-driver/mysql"
	"github.com/joho/godotenv"
	_ "github.com/joho/godotenv"

	swagger "github.com/arsmn/fiber-swagger/v2"

	// docs are generated by Swag CLI, you have to import them.
	// replace with your own docs folder, usually "github.com/username/reponame/docs"
	_ "talui/docs"
)

func main() {
	fiberApp := app.CreateFiberApp()
	
	_ = godotenv.Load(".env")
	fiberApp.Use(cors.New())
	fiberApp.Use(cors.New(cors.Config{
	    AllowOrigins:     "*",
	    AllowMethods:     "GET,POST,HEAD,PUT,DELETE,PATCH",
	    AllowHeaders:     "",
	}))
	
	fiberApp.Get("/swagger/*", swagger.Handler) // default
    
    mysqlUri := os.Getenv("MYSQL_URI")
	database.ConnectMySQL(mysqlUri)
	// middleware.RegisDb(fiberApp, db)
	route.SetupRouter(fiberApp)
	
	// port 
	port := os.Getenv("SERVER_PORT")
	fmt.Printf("starting server at port %s", port)
	fiberApp.Listen(":" + port)
}