// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "basePath": "/",
    "swagger": "2.0",
    "securityDefinitions": {},
    "host": "talui-ku-server.herokuapp.com",
    "consumes": [
      "application/json"
    ],
    "definitions": {},
    "info": {
      "license": {
        "name": "ISC"
      },
      "title": "TaluiKU Api docs",
      "version": "0.1.0"
    },
    "paths": {
      "/complete/getAllTalui":{
        "get": {
          "operationId": "completeAlle",
          "produces": [
            "application/json"
          ],
          "responses": {
            "200": {
              "description": "Ok",
              "schema": {
                "type": "string"
              }
            }
          },
          "description": ""
        }
      },
      "/on/getAllTalui": {
        "get": {
          "operationId": "onAll",
          "produces": [
            "application/json"
          ],
          "responses": {
            "200": {
              "description": "Ok",
              "schema": {
                "type": "string"
              }
            }
          },
          "description": ""
        }
      },
      "/complete/insertTalui":{
        "post": {
          "operationId": "Insert Complete",
          "produces": [
            "application/json"
          ],
          "parameters": [
          {
            "name": "entry",
            "in": "query",
            "description": "entry",
            "required": false,
            "type": "string",
            "items": {
              "type": "string"
            }
          },
          {
            "name": "dest",
            "in": "query",
            "description": "dest",
            "required": false,
            "type": "string",
            "items": {
              "type": "string"
            }
          },
          {
            "name": "line",
            "in": "query",
            "description": "line",
            "required": false,
            "type": "string",
            "items": {
              "type": "string"
            }
          }
        ],
          "responses": {
            "200": {
              "description": "Ok",
              "schema": {
                "type": "string"
              }
            }
          },
          "description": ""
        }
      },
      "/on/insertTalui":{
        "post": {
          "operationId": "InsertOn",
          "produces": [
            "application/json"
          ],
          "parameters": [
          {
            "name": "entry",
            "in": "query",
            "description": "entry",
            "required": false,
            "type": "string",
            "items": {
              "type": "string"
            }
          },
          {
            "name": "dest",
            "in": "query",
            "description": "dest",
            "required": false,
            "type": "string",
            "items": {
              "type": "string"
            }
          },
          {
            "name": "line",
            "in": "query",
            "description": "line",
            "required": false,
            "type": "string",
            "items": {
              "type": "string"
            }
          }
        ],
          "responses": {
            "200": {
              "description": "Ok",
              "schema": {
                "type": "string"
              }
            }
          },
          "description": ""
        }
      },
      "/arriveAt":{
        "post": {
          "operationId": "arr",
          "produces": [
            "application/json"
          ],
          "parameters": [
          {
            "name": "dest",
            "in": "query",
            "description": "dest",
            "required": false,
            "type": "string",
            "items": {
              "type": "string"
            }
          },
          {
            "name": "line",
            "in": "query",
            "description": "line",
            "required": false,
            "type": "string",
            "items": {
              "type": "string"
            }
          }
        ],
          "responses": {
            "200": {
              "description": "Ok",
              "schema": {
                "type": "string"
              }
            }
          },
          "description": ""
        }
      },
      "/station/using/entry":{
        "get": {
          "operationId": "getE",
          "produces": [
            "application/json"
          ],
          "responses": {
            "200": {
              "description": "Ok",
              "schema": {
                "type": "string"
              }
            }
          },
          "description": ""
        }
      },
      "/station/using/dest":{
        "get": {
          "operationId": "getD",
          "produces": [
            "application/json"
          ],
          "responses": {
            "200": {
              "description": "Ok",
              "schema": {
                "type": "string"
              }
            }
          },
          "description": ""
        }
      },
      "/station/find/entry":{
        "get": {
          "operationId": "getUE",
          "produces": [
            "application/json"
          ],
          "responses": {
            "200": {
              "description": "Ok",
              "schema": {
                "type": "string"
              }
            }
          },
          "description": ""
        }
      },
      "/station/find/dest":{
        "get": {
          "operationId": "getUD",
          "produces": [
            "application/json"
          ],
          "responses": {
            "200": {
              "description": "Ok",
              "schema": {
                "type": "string"
              }
            }
          },
          "description": ""
        }
      }
    },
    "produces": [
      "application/json"
    ]
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "talui-ku-server.herokuapp.com/",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Talui Api docs",
	Description: "This is a sample swagger for Fiber",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
